### ISSUE TITLE
Missing JAXB dependency on Java 10

### ISSUE THREAD

**Issue by sneumann** [lifs-tools/jmzTab-m#18]
Hi,
On newer Java's (here. openjdk 10.0.1) I get a java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException. This is because newer java (since 1.9) have removed them from
the ClassPath [1]. Hence, a new dependency has to be added explicitly.

PR coming.
Yours,
Steffen

[1] https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by nilshoffmann** [comment]
Fixed in 326006f5c1a12bd78f45903948548c421b2fc610
