### ISSUE TITLE
Matching cardinality of ambiguity

### ISSUE THREAD

**Issue by sneumann** [lifs-tools/jmzTab-m#19]
Hi, does the validator capture if e.g. in the SML we have four ambiguous smiles `A|B|C|D` but there are three ambiguous InChIs `X|Y|Z` ? 

For now this is just a question, but if the answer is no, it is an issue ;-)

**Comment by nilshoffmann** [comment]
Please check https://github.com/nilshoffmann/jmzTab-m/blob/efcf726049415b728f87ae015fd3318ee04f4743/io/src/main/java/uk/ac/ebi/pride/jmztab2/utils/parser/SMLLineParser.java#L198 and the following lines. This part *SHOULD* enforce that the cardinality for the fields 
database_identifier, chemical_formula, smiles, inchi, chemical_name, uri and theoretical_neutral_mass are the same as stated by the spec, starting at: 
https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-developments/2_0-Metabolomics-Draft/mzTab_format_specification_2_0-M_draft.adoc#633-database_identifier

**Comment by nilshoffmann** [comment]
The validator checks that these fields have the same number of elements.
