### ISSUE TITLE
Character for seperation of study variables 

### ISSUE THREAD

**Issue by SurajViitk** [lifs-tools/jmzTab-m#30]
study_variables[1-n]-[assay_refs](https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-releases/2_0-Metabolomics-Release/mzTab_format_specification_2_0-M_release.adoc#6240-study_variable1-n-assay_refs) is supposed to be bar separated, but currently a comma separated values are parsed correctly instead.

**Comment by nilshoffmann** [comment]
Currently pushing the SNAPSHOT to sonatype snapshots. Please check this section to use the SNAPSHOT version:
https://github.com/lifs-tools/jmzTab-m#using-development-snapshots
