### ISSUE TITLE
getAssayfor() Optional Column possible correction

### ISSUE THREAD

**Issue by SurajViitk** [lifs-tools/jmzTab-m#31]
I think m.matches() [here](https://github.com/lifs-tools/jmzTab-m/blob/a98275cb21ee3a8921ce3af8e8648c0992dfb662/api/src/main/java/de/isas/mztab2/model/MzTabAccess.java#L113) should be replaced with m.find() because a possible value for identifier is assay[1]_peak_mz or as given in [this](https://github.com/lifs-tools/jmzTab-m/blob/a98275cb21ee3a8921ce3af8e8648c0992dfb662/api/src/main/java/de/isas/mztab2/model/MzTabAccess.java#L113) example, it could be assay[1]_my_value for which m.matches() will give false

**Comment by nilshoffmann** [comment]
@SurajViitk Snapshot build has been deployed. Please test!

**Comment by SurajViitk** [comment]
test done, working fine
